services:
  - type: static
    name: frontend
    path: .
    buildCommand: "echo 'No build command'"
    publishDirectory: "."
    routes:
      - src: /(.*)
        dest: /index.html

  - type: web
    name: backend
    path: nodeServer
    buildCommand: "npm install"
    startCommand: "node index.js"
